### ISSUE TITLE
Non-Ascii character breaks setup py

### ISSUE THREAD

**Issue by sjzabel** [davisp/ghp-import#28]
The 'î' in "Benoît Chesneau" ala...

(py3)➜  ghp-import git:(master) python setup.py install                                                              master
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    LONG_DESC = open(os.path.join(os.path.dirname(**file**), "README.md")).read()
  File "/Users/szabel/.virtualenvs/py3/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1362: ordinal not in range(128)

**Comment by sjzabel** [comment]
Pull request #31 is prolly the correct fix.
