### ISSUE TITLE
Fails when git config user.name contains non-ascii characters

### ISSUE THREAD

**Issue by royaltm** [davisp/ghp-import#73]
When trying to use it, I get an error:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\ghp-import-script.py", line 9, in <module>
    load_entry_point('ghp-import==0.5.5', 'console_scripts', 'ghp-import')()
  File "c:\python27\lib\site-packages\ghp_import.py", line 238, in main
    run_import(git, args[0], opts)
  File "c:\python27\lib\site-packages\ghp_import.py", line 173, in run_import
    start_commit(pipe, git, opts.branch, opts.mesg)
  File "c:\python27\lib\site-packages\ghp_import.py", line 128, in start_commit
    write(pipe, enc('committer %s <%s> %s\n' % (uname, email, mk_when())))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8c in position 11: ordinal not in range(128)
```

my `user.name=Rafał Michalski` if I replace utf-8 `ł` with ascii `l` it works.

**Comment by royaltm** [comment]
ok, my bad, the problem was in:
```
time.strftime('%z')
'\x8crodkowoeuropejski czas stand.'
```

**Comment by royaltm** [comment]
ok, this is a known problem with python on windows, closing
